# Generated by Django 4.1.1 on 2022-11-03 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={},
        ),
    ]
